<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BlaisePascal.SmartSchoolApp.Domain\BlaisePascal.SmartSchoolApp.Domain.csproj" />
    <ProjectReference Include="..\..\BlaisePascal.SmartSchoolApp.SharedKernelf\BlaisePascal.SmartSchoolApp.SharedKernel.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
